### ISSUE TITLE
Thanks so much! Perhaps a more visually appealing docs page would be better.

### ISSUE THREAD

**Issue by jasonminsookim** [TyberiusPrime/dppd#2]
Hello,

As a user of both R and Python, I loved dplyr and ggplot. I tried out the plydata and plotnine implementations but felt that it was lacking the pythonic style. In particular, I struggled to filter dataframes to exclude rows that have a null value for a specific column. I love how I can use both pandas and the common dplyr verbs. I am amazed at how this isn't the defacto standard wrapper library for pandas. Great work! I'll be sure to checkout your implementation of plotnine, but have been very impressed with plotly express.

One suggestion to increase the popularity of this amazing library would be to have prettier documentation. The next and previous topics were a little bit awkward to navigate.

**Comment by pwwang** [comment]
@jasonminsookim Probably check out datar:
https://github.com/pwwang/datar

A closer port of dplyr and related packages from R to python.
